apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default

  source:
    # GitOps repository.
    repoURL: 'https://github.com/GreatSoravit/aws-argocd-explore.git'
    
    # This is the branch Argo CD should watch. 'HEAD' means the default branch (usually 'main').
    targetRevision: HEAD
    
    # The folder inside your GitOps repo where your Kubernetes manifests are located.
    path: .

  # This section tells Argo CD WHERE to deploy your application (the destination).
  destination:
    # This URL means "deploy to the same cluster where Argo CD is running."
    server: 'https://kubernetes.default.svc'
    namespace: webapp

  # This section configures the automation.
  syncPolicy:
    # This enables automatic syncing. When Argo CD sees a change in Git, it will apply it.
    automated:
      # This tells Argo CD to delete resources that are removed from Git.
      prune: true
      # This tells Argo CD to automatically fix any manual changes made to the cluster.
      selfHeal: true
